#!/usr/bin/env ruby

require 'todo-txt'

# Configuration variables
$todo_file = "/home/sam/Dropbox/todo/todo.txt"
$title     = "Todo: %P %p %c"

def parse_title title, task
  title.gsub('%c', task.contexts.join(', ')).
        gsub('%p', task.projects.join(', ')).
        gsub('%P', task.priority).
        gsub(/\s+/, ' ')
end

list  = Todo::List.new $todo_file
task  = list.sample

title   = parse_title $title, task
content = task.text

`notify-send "#{title}" "#{content}"`
